select @@VERSION;
use master
GO
drop DATABASE QL_NhaSach_DA_DotNet
GO
CREATE DATABASE QL_NhaSach_DA_DotNet
GO
use QL_NhaSach_DA_DotNet

CREATE TABLE NHANVIEN
(
	MaNV varCHAR(5) NOT NULL ,
	password varchar(6),
	TenNV NVARCHAR(50),
	DiaChi NVARCHAR(50),
	GioiTinh NVARCHAR(3),
	SDT NCHAR(10),
	roles int,
	PRIMARY KEY (manv)
)
--CREATE TABLE DangNhap
--(
--	username CHAR(5),
--	PassWord nchar(10),
--	primary key(username)
--	--CONSTRAINT FK_tknv FOREIGN KEY (username) REFERENCES nhanvien(manv)
--)

CREATE TABLE KhachHang
(
	MaKH NCHAR(10) PRIMARY KEY ,
	TenKH NVARCHAR(50) ,
	DiaChi NVARCHAR(50),
	GioiTinh NVARCHAR(3),
	SDT NCHAR(10)
)

--CREATE TABLE THELOAI
--(
--	MaTL NCHAR(10) NOT NULL PRIMARY KEY ,
--	TenTL NVARCHAR(50) 
--)

CREATE TABLE HOADON
(
	MaHD nchar(10) PRIMARY KEY,
	NgayMua Datetime,
	MaKH NCHAR(10) ,
	MaNV varCHAR(5),
	TongTien money
)

CREATE TABLE CT_HOADON
(
	MaHD nchar(10),
	MaSach NCHAR(10),
	SoLuong int,
	ThanhTien money,
	primary key(MaHD,MaSach)
)


CREATE TABLE KHO
(
	MaSach NCHAR(10), 
	SLTon int,
	DonGiaNhap money,
	DonGiaBan money,

)


CREATE TABLE PHIEUNHAP
(
	MaPN NCHAR(10) NOT NULL PRIMARY KEY,
	NgayNhap Datetime,
	MaNV varCHAR(5)
)

CREATE TABLE CT_PHIEUNHAP
(
	MaPN NCHAR(10),

	MaSach NCHAR(10),
	MaTL NCHAR(10),
	MaTG NCHAR(10),

	SoLuong int,
	DonGia money,

	primary key(MaPN,MaSach)
	
)

CREATE TABLE TACGIA
(
	MaTG NCHAR(10) NOT NULL PRIMARY KEY ,
	TenTG nvarchar(40)
)
CREATE TABLE NXB
(
	MaNXB NCHAR(10) NOT NULL PRIMARY KEY,
	TenNXB nvarchar(40)
)

CREATE TABLE SACH
(
	MaSach NCHAR(10) NOT NULL PRIMARY KEY,
	TenSach NVARCHAR(50) NOT NULL ,
	GiaNhap MONEY,
	GiaBia MONEY,

	MaTL NCHAR(10),
	MaTG NCHAR(10),
	MaNXB NCHAR(10),

)
create table PHANQUYEN
(
	roles int PRIMARY KEY,
	tenRoles nvarchar(40) 
)



--ALTER TABLE SACH ADD CONSTRAINT FK_SACH_TL FOREIGN KEY (MaTL) REFERENCES THELOAI(MaTL)
ALTER TABLE SACH ADD CONSTRAINT FK_SACH_TG FOREIGN KEY (MaTG) REFERENCES TACGIA(MaTG)
ALTER TABLE SACH ADD CONSTRAINT FK_SACH_NXB FOREIGN KEY (MaNXB) REFERENCES NXB(MaNXB)

go

ALTER TABLE CT_PHIEUNHAP ADD CONSTRAINT FK_PN FOREIGN KEY (MaPN) REFERENCES PHIEUNHAP(MaPN)
ALTER TABLE CT_PHIEUNHAP ADD CONSTRAINT FK_CTPN_S FOREIGN KEY (MaSach) REFERENCES SACH(MaSach)
 go

ALTER TABLE PHIEUNHAP ADD CONSTRAINT FK_PN_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV) 

ALTER TABLE KHO ADD CONSTRAINT FK_K_S FOREIGN KEY (MaSach) REFERENCES SACH(MaSach)

ALTER TABLE CT_HOADON ADD CONSTRAINT FK_HD_S FOREIGN KEY (MaSach) REFERENCES SACH(MaSach)
ALTER TABLE CT_HOADON ADD CONSTRAINT FK_HD FOREIGN KEY (MaSach) REFERENCES HOADON(MaHD)
go
ALTER TABLE HOADON ADD CONSTRAINT FK_HD_KH FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH)
ALTER TABLE HOADON ADD CONSTRAINT FK_HD_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV) 

ALTER TABLE NHANVIEN ADD CONSTRAINT FK_ROLES_NV FOREIGN KEY (roles) REFERENCES PHANQUYEN(roles)










--INSERT INTO TACGIA
--VALUES(NULL,'Phạm Thị Yến Nhi')

--SELECT * FROM KhachHang
SELECT * FROM NHANVIEN

--INSERT INTO KhachHang
--VALUES(NULL,N'Phạm Thị Yến Nhi',N'Bạc Liêu',N'Nữ','0944777')


INSERT INTO NHANVIEN(MaNV,password)
VALUES('admin','admin')

--INSERT INTO DangNhap
--VALUES('nv01','123456')

--SELECT CONCAT('KH', RIGHT(CONCAT('0000000000',ISNULL(right(max(MaKH),10),0) + 1),10))
--                                            FROM dbo.KhachHang where MaKH like 'A%'
--SELECT CONCAT('KH', RIGHT(CONCAT('000000',ISNULL(right(max(MaKH),10),0) + 1),10)) FROM dbo.KhachHang where MaKH like 'A%'

SELECT * FROM SACH

SELECT * FROM NHANVIEN
SELECT * FROM HOADON
SELECT * FROM CT_HOADON
SELECT * FROM tacgia
SELECT * FROM PHIEUNHAP
SELECT * FROM SACH
SELECT * FROM KhachHang
SELECT * FROM THELOAI
SELECT * FROM NXB
SELECT * FROM KHO



--INSERT INTO NHANVIEN
--VALUES
--('nv01',N'Nhân viên 01',N'Ninh Bình','Nam','665565656')


--INSERT INTO HOADON
--VALUES('hd01','10/30/2023',N'Hà Tiên','Nam','123456777')

--SELECT TenNV FROM NHANVIEN
--where MaNV = 'nv07'





go

INSERT INTO PHANQUYEN
VALUES
('1','admin'),
('2','Nhân viên')
